name: flutter_ai_age
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # http: ^0.13.0
  # graphql: ^5.1.3 # 5.1.3

  http: ^1.3.0
  graphql: ^5.1.3 # 5.2.0-beta.10
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
